[libraries]

bankBcp = { module = "com.bcp.bank.bcp:library", version.ref = "bankBcp" }
bankBcpFeatureEnrollment = { module = "com.bcp.bank.bcp.feature.enrollment:library", version.ref = "bankBcpFeatureEnrollment" }
bankBcpMaps = { module = "com.bcp.bank.bcp.maps:library", version.ref = "bankBcpMaps" }
bankBcpModulemanager = { module = "com.bcp.bank.bcp.modulemanager:library", version.ref = "bankBcpModulemanager" }
bankModelbcp = { module = "com.bcp.bank.modelbcp:library", version.ref = "bankModelbcp" }
bankNavigator = { module = "com.bcp.bank.navigator:library", version.ref = "bankNavigator" }
bankUsuallyData = { module = "com.bcp.bank.usually.data:library", version.ref = "bankUsuallyData"}
bankUtil = { module = "com.bcp.bank.util:library", version.ref = "bankUtil" }