[versions]

bankBcp = "1.0.0"
bankBcpFeatureEnrollment = "1.0.0"
bankBcpMaps = "1.0.0"
bankBcpModulemanager = "1.0.0"
bankModelbcp = "1.0.0"
bankNavigator = "1.0.0"
bankUsuallyData = "1.0.0"
bankUtil = "1.0.0"