[versions]

bankLinter = "1.0.0"

ciam = "1.3.15"
mbbkCiamCert = "1.3.15-EH"
mbbkCiamEthical = "1.3.15-EH-SNAPSHOT"
mbbkCiamSnapshot = "1.3.16-SNAPSHOT" # "1.3.15-SNAPSHOT"

coreAuth = "1.2.5"
coreAuthSnapshot = "1.2.5-EH-SNAPSHOT" #"1.2.5-SNAPSHOT"
coreAuthCert = "1.2.5-EH"
coreAuthEthical = "1.2.5-EH-SNAPSHOT"

coreNetworking = "2.3.5"
coreNetworkingSnapshot = "2.3.5-SNAPSHOT"
coreNetworkingEthical = "0.0.3-EH-SNAPSHOT"

coreResources = "2.0.0"
coreStorage = "1.1.0"
coreUtil = "1.0.0"
coreMbbkUiComponent = "1.3.20-SNAPSHOT" # "1.3.19"
corePushnotification = "1.0.2"

cpClientLibraryBcp = "3.0.9"
mobilepaymentVisasensorbranding = "1.0.0"

facialAuthAndroidMbbkSnapshot = "1.9.7-SNAPSHOT"
facialAuthAndroidMbbk = "1.9.7"
facialAuthAndroidBcpEhEthical = "0.0.3-SNAPSHOT"

masivPushAndroidSDK = "1.1.3"

medalliaAndroidSdk = "4.0.2"
jacksonCoreJacksonDatabind = "2.10.1"