[versions]

bankLinter = "1.0.0"

ciam = "1.3.21"
mbbkCiamCert = "1.3.21-EH"
mbbkCiamEthical = "1.3.21-EH-SNAPSHOT"
mbbkCiamSnapshot = "1.3.21-20240311.203039-10"

coreAuth = "1.2.7"
coreAuthSnapshot = "1.2.7-20240311.191844-8"
coreAuthCert = "1.2.7-EH"
coreAuthEthical = "1.2.7-EH-SNAPSHOT"

coreNetworking = "2.3.5"
coreNetworkingSnapshot = "2.3.5-SNAPSHOT"
coreNetworkingEthical = "0.0.3-EH-SNAPSHOT"

coreMbbkUiComponent = "1.3.26"
coreMbbkUiComponentCert = "1.3.26-EH"
coreMbbkUiComponentSnapshot = "1.3.26-20240220.025328-4"

coreResources = "2.5.0"
coreStorage = "1.1.0"
coreUtil = "1.0.0"
corePushnotification = "1.0.2"
coreUiComponent = "2.4.1"
uiMbbkKeyboardSnapshot = "1.4.7-20240307.220715-2"
uiMbbkKeyboard = "1.4.7"

cpClientLibraryBcp = "3.0.9"
mobilepaymentVisasensorbranding = "1.0.0"

facialAuthAndroidMbbkSnapshot = "3.3.12-20230731.144911-1"
facialAuthAndroidMbbk = "3.3.12"
facialAuthAndroidBcpEhEthical = "0.0.3-SNAPSHOT"

masivPushAndroidSDK = "1.1.3"

medalliaAndroidSdk = "4.0.2"

coreOtp = "0.1.0"