[versions]

bankLinter = "1.0.0"

ciam = "1.3.27"
mbbkCiamCert = "1.3.27.06-EH"
mbbkCiamEthical = "1.3.27-EH-SNAPSHOT"
mbbkCiamSnapshot = "1.3.27.06-20241016.224012-5"

coreAuth = "1.2.9"
coreAuthCert = "1.2.9.06-EH"
coreAuthEthical = "1.2.9-EH-SNAPSHOT"
coreAuthSnapshot = "1.3.06-20241014.203804-1"

coreNetworking = "2.7.0"
coreNetworkingSnapshot = "2.7.0-SNAPSHOT"
coreNetworkingEthical = "0.0.3-EH-SNAPSHOT"

coreMbbkUiComponent = "1.3.28"
coreMbbkUiComponentCert = "1.3.28-EH"
coreMbbkUiComponentSnapshot = "1.3.28-SNAPSHOT"

coreResources = "2.5.0"
coreStorage = "1.4.0"
coreUtil = "1.0.0"
coreUiComponent = "2.4.1"
uiMbbkKeyboardSnapshot = "1.4.9-20240807.212122-2"
uiMbbkKeyboard = "1.4.9"

cpClientLibraryBcp = "3.0.9"
mobilepaymentVisasensorbranding = "1.0.0"

facialAuthAndroidMbbkSnapshot = "6.3.0-SNAPSHOT"
facialAuthAndroidMbbk = "6.3.0"
facialAuthAndroidBcpEhEthical = "0.0.3-SNAPSHOT"

masivPushAndroidSDK = "1.1.3"

medalliaAndroidSdk = "4.0.2"

coreOtp = "0.1.0"

wrdaAndroidSdk = "1.2.0"
wrdaAndroidSdkCert = "1.1.902-CERT"
wrdaAndroidSdkSnapshot = "1.1.902-CERT-SNAPSHOT"

qrScanSnapshot = "1.0.2-SNAPSHOT"
qrScan = "1.0.2"