[versions]

bankLinter = "1.0.0"

ciam = "1.5.2"
mbbkCiamCert = "1.5.2-EH"
mbbkCiamEthical = "1.5.0-EH-SNAPSHOT"
mbbkCiamSnapshot = "1.5.01-20241115.170300-4"

coreAuth = "1.4.1"
coreAuthCert = "1.4.1-EH"
coreAuthEthical = "1.4.1-EH-SNAPSHOT"
coreAuthSnapshot = "1.4.1-20241028.224254-1"

coreNetworking = "2.7.0"
coreNetworkingSnapshot = "2.7.0-SNAPSHOT"
coreNetworkingEthical = "0.0.3-EH-SNAPSHOT"

coreMbbkUiComponent = "1.3.28"
coreMbbkUiComponentCert = "1.3.28-EH"
coreMbbkUiComponentSnapshot = "1.3.28-SNAPSHOT"

coreResources = "3.1.1"
coreStorage = "1.5.0"
coreUtil = "1.0.0"
coreUiComponent = "2.5.1"
coreUiComponentCompose = "1.0.0"
coreUiComponentComposeCert = "1.0.0"
coreUiComponentComposeSnapshot = "1.0.0-SNAPSHOT"
uiMbbkKeyboardSnapshot = "1.5.0-20241029.210740-2"
uiMbbkKeyboard = "1.5.0"

cpClientLibraryBcp = "3.0.9"
mobilepaymentVisasensorbranding = "1.0.0"

facialAuthAndroidMbbkSnapshot = "6.3.1-SNAPSHOT"
facialAuthAndroidMbbk = "6.3.1"
facialAuthAndroidBcpEhEthical = "0.0.3-SNAPSHOT"

masivPushAndroidSDK = "1.1.3"

medalliaAndroidSdk = "4.0.2"

coreOtp = "0.1.0"

wrdaAndroidSdk = "1.4.1"
wrdaAndroidSdkCert = "1.4.1-CERT"
wrdaAndroidSdkSnapshot = "1.4.1-20241129.172124-2"

qrScanSnapshot = "1.0.2-SNAPSHOT"
qrScan = "1.0.2"