[versions]

bankLinter = "1.0.0"

ciam = "1.3.27"
mbbkCiamCert = "1.3.27-EH"
mbbkCiamEthical = "1.3.27-EH-SNAPSHOT"
mbbkCiamSnapshot = "1.3.27.30.6-20240906.170638-3"

coreAuth = "1.2.9"
coreAuthCert = "1.2.9-EH"
coreAuthEthical = "1.2.9-EH-SNAPSHOT"
coreAuthSnapshot = "1.2.9.01-20240816.153649-4"

coreNetworking = "2.7.0"
coreNetworkingSnapshot = "2.7.0-SNAPSHOT"
coreNetworkingEthical = "0.0.3-EH-SNAPSHOT"

coreMbbkUiComponent = "1.3.27"
coreMbbkUiComponentCert = "1.3.27-EH"
coreMbbkUiComponentSnapshot = "1.3.27-20240428.053351-3"

coreResources = "2.5.0"
coreStorage = "1.4.0"
coreUtil = "1.0.0"
coreUiComponent = "2.4.1"
uiMbbkKeyboardSnapshot = "1.4.9-20240807.212122-2"
uiMbbkKeyboard = "1.4.9"

cpClientLibraryBcp = "3.0.9"
mobilepaymentVisasensorbranding = "1.0.0"

facialAuthAndroidMbbkSnapshot = "6.0.1-SNAPSHOT"
facialAuthAndroidMbbk = "6.0.1"
facialAuthAndroidBcpEhEthical = "0.0.3-SNAPSHOT"

masivPushAndroidSDK = "1.1.3"

medalliaAndroidSdk = "4.0.2"

coreOtp = "0.1.0"

wrdaAndroidSdk = "1.0.2"
wrdaAndroidSdkCert = "1.0.2"
wrdaAndroidSdkSnapshot = "1.0.2-20240816.003324-100"

qrScanSnapshot = "1.0.2-SNAPSHOT"
qrScan = "1.0.2"