[versions]

bankLinter = "1.0.0"

ciam = "1.3.20"
mbbkCiamCert = "1.3.20-EH"
mbbkCiamEthical = "1.3.15-EH-SNAPSHOT"
mbbkCiamSnapshot = "1.3.20-EH-SNAPSHOT" # "1.3.18-SNAPSHOT"

coreAuth = "1.2.6"
coreAuthSnapshot = "1.2.6-EH-SNAPSHOT"
coreAuthCert = "1.2.6-EH"
coreAuthEthical = "1.2.5-EH-SNAPSHOT"

coreNetworking = "2.4.0"
coreNetworkingSnapshot = "2.4.0-SNAPSHOT"
coreNetworkingEthical = "0.0.3-EH-SNAPSHOT"

coreResources = "1.4.5"
coreStorage = "1.1.0"
coreUtil = "1.0.0"
coreMbbkUiComponent = "1.3.24"
corePushnotification = "1.0.2"
coreUiComponent = "2.3.0"
uiMbbkKeyboardSnapshot = "1.4.5-SNAPSHOT"
uiMbbkKeyboard = "1.4.5"

cpClientLibraryBcp = "3.0.9"
mobilepaymentVisasensorbranding = "1.0.0"

facialAuthAndroidMbbkSnapshot = "3.3.12-20230731.144911-1"
facialAuthAndroidMbbk = "3.3.12"
facialAuthAndroidBcpEhEthical = "0.0.3-SNAPSHOT"

masivPushAndroidSDK = "1.1.3"

medalliaAndroidSdk = "4.0.2"

wrdaAndroidSdk = "1.0.4"
wrdaAndroidSdkSnapshot = "1.0.2.10-SNAPSHOT"#"1.0.4-SNAPSHOT"

coreOtp = "0.1.0"