[libraries]
core-network = { module = "com.bcp.core:networking", version.ref = "core-network" }
core-util = { module = "com.bcp.core:util", version.ref = "core-util" }
core-storage = { module = "com.bcp.core:storage", version.ref = "core-storage" }
core-UIComponent = { module = "com.bcp.core.mbbk:ui-component", version.ref = "core-uiComponent" }
core-resources = { module = "com.bcp.core:resources", version.ref = "core-resources" }

core-auth = { module = "com.bcp.core:auth", version.ref = "core-auth" }


ciam = { module = "com.bcp.core.mbbk:ciam", version.ref = "ciam" }