[versions]

appcompat = "1.3.0"
coreKtx = "1.3.2"
browser = "1.3.0"
constraintlayout = "2.1.4"
biometric = "1.0.1"
androidxViewpager2 = "1.0.0"
coreSplashscreen = "1.0.0"
annotation = "1.5.0"

lifecycleExtensions = "2.2.0"
lifecycleViewmodelKtx = "2.2.0"
lifecycleCommonJava8 = "2.4.1"
lifecycleRuntimeKtx = "2.5.1"
recyclerView = "1.1.0"

supportCardViewV7 = "29.0.0"
navigationFragmentKtx = "2.7.7"
navigationUiKtx = "2.5.1"
navigationDynamicFeaturesFragment = "2.5.1"
navigationSafeArgsGradlePlugin = "2.5.1"
fragmentcompose = "1.8.3"



googlePlayCore = "1.10.3"
googleFeatureDelivery = "2.1.0"
material = "1.11.0"
googlePlayCoreKtx = "1.8.1"
androidxCoreKtx = "1.13.1"
googlePlayReview = "2.0.1"
googlePlayReviewKtx = "2.0.1"
googleFeatureDeliveryKtx = "2.1.0"
gmsGoogleServices = "4.3.14"
gmsPlayServicesMlkitTextRecognition = "18.0.0"

playServicesAuth = "20.3.0"
playServicesAuthApiPhone = "18.0.1"
playServicesLocation = "17.1.0"
playServicesPlaces = "17.0.0"

hmsLocation = "6.7.0.300"
hmsMaps = "5.0.3.302"

facebookShimmer = "0.5.0"

suportMultidex = "1.0.3"

firebaseMessagingKtx = "20.3.0"
firebaseFirestoreKtx = "24.11.1"

androidMapsUtils = "2.1.0"
artifactory-plugin = "4.1.1"
compileSdk = "34"

dynatraceAgentAndroid = "8.263.1.1002"
dynatraceGradlePlugin = "8.263.1.1002"

androidGradlePlugin = "8.1.4"
gradleMavenPluginPublish = "0.18.0"
gson = "2.8.6"
jfrogBuildInfoExtractorGradle = "4.31.9"
jvmTarget = "11"
kotlin = "1.9.24"

airbnbLottie = "5.0.3"

mbbk-plugin = "1.0.1.lts"
minSdk = "28"

roomCompiler = "2.2.5"
roomKtx = "2.2.5"
roomRuntime = "2.2.5"
targetSdk = "34"
workRuntime = "2.7.0"

testJUnit = "4.13.2"
testMockitoCore = "4.3.1"
testMockitoInline = "3.3.3"
nhaarmanTestMockitoKotlin = "2.2.0"
jetbrainsTestKotlinxCoroutineTest = "1.6.4"
androidArchCoreTesting = "2.2.0"
ioMockk = "1.13.3"
mockwebserver = "4.10.0"
turbine = "0.9.0"
hamcrest = "2.2"
assertjCore = "3.21.0"
androidxTestjUnit = "1.1.5"

androidTestRunner = "1.5.1"
androidxTestExpressoCore = "3.5.1"

guardsquareDexguardGradlePlugin = "9.8.8"
guardsquareDexguard = "9.8.8"

jetbrainsKotlinxCoroutines = "1.6.4"

adobeAnalytics = "1.2.10"
adobeMobileservices = "1.1.5"
adobeUserprofile = "1.1.0"
adobeSdkCore = "1.11.0"
adobeTarget = "1.4.0"
adobeCampaignClassic = "1.0.1"

rsa = "6.2.5"
mfaSecurIDLib = "4.0.2.4"

gradlePluginPublish = "0.9.9"
dcendentsAndroidMavenGradlePlugin = "1.5"

jetbrainsKotlinxMetadataJvm = "0.5.0"

detektGradlePlugin = "1.15.0"

huaweiAgcp = "1.5.2.300"

sonarqubeGradlePlugin = "3.4.0.2513"

facephi = "12.0"
jacksonCoreJacksonDatabind = "2.10.1"
coilSvg = "1.4.0"
facebookSdkCore = "16.0.0"

firebaseVersionBoom = "32.5.0"
firebaseGradle = "2.9.9"
hilt = "2.48"

tpcSdk = "1.11.1"
okhttp = "4.9.1"
jna = "5.5.0"
playServicesBase="18.5.0"

composeBom = "2024.09.01"
composeNavigation = "2.8.0"
composeLifecycle = "2.8.5"
constraintlayoutCompose = "1.0.1"
activityCompose = "1.9.2"

kotlinCompilerExtension = "1.5.14"
systemuicontrollerCompose = "0.30.1"

