[versions]

androidMapsUtils = "2.1.0"
appcompat = "1.3.1"
artifactory-plugin = "4.1.1"
browser = "1.3.0"
compileSdk = "31"
constraintlayout = "1.1.3"
coreKtx = "1.6.0"
dynatraceAgentAndroid = "8.217.1.1003"
gradle = "7.1.3"
gradleMavenPluginPublish = "0.18.0"
gson = "2.8.2"
huaweiHmsLocation = "5.0.0.301"
huaweiHmsMaps = "5.0.3.302"
jfrogBuildInfoExtractorGradle = "4.15.1"
junit = "4.13.2"
jvmTarget = "1.8"
kotlinGradle = "1.6.21"
lifecycleExtensions = "2.1.0"
lifecycleViewmodelKtx = "2.2.0"
lottie = "3.5.0"
material = "1.4.0"
mbbk-plugin = "1.0.1.lts"
minSdk = "21"
navigationFragmentKtx = "2.3.0"
navigationUiKtx = "2.3.0"
playServicesAuthApiPhone = "17.4.0"
playServicesLocation = "17.1.0"
playServicesPlaces = "17.0.0"
roomCompiler = "2.2.5"
roomKtx = "2.2.5"
roomRuntime = "2.2.5"
rsaSecurIDLib = "2.8.0"
targetSdk = "31"