[bundles]
buildScriptDependencies = [
    "gradle",
    "kotlinGradlePlugin",
    "gradleMavenPluginPublish"
]

baseImplementation = [
    "coreKtx",
    "material"
]

baseTestImplementation = [
    "junit"
]