[libraries]

appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "androidxViewpager2" }
androidx-coreSplashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }

androidx-lifecycleExtensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions"}
androidx-lifecycleViewmodelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-lifecycleCommonJava8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycleCommonJava8" }
androidx-lifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

support-cardviewV7 = { module = "com.android.support:cardview-v7", version.ref = "supportCardViewV7" }

navigation-fragmentKtx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
navigation-uiKtx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationUiKtx" }
navigation-dynamicFeaturesFragment = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "navigationDynamicFeaturesFragment" }
navigation-safeArgsGradlePlugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigationSafeArgsGradlePlugin" }

androidx-roomCompiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-roomKtx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-roomRuntime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }

google-playCore = { module = "com.google.android.play:core", version.ref = "googlePlayCore" }
google-featureDelivery = { module = "com.google.android.play:feature-delivery", version.ref = "googleFeatureDelivery" }
google-material = { module = "com.google.android.material:material", version.ref = "material" }
google-playCoreKtx = { module = "com.google.android.play:core-ktx", version.ref = "googlePlayCoreKtx" }
androidx-coreKtx = { module = "androidx.core:core-ktx", version.ref = "androidxCoreKtx" }
google-featureDeliveryKtx = { module = "com.google.android.play:feature-delivery-ktx", version.ref = "googleFeatureDeliveryKtx" }
google-androidMapsUtils = { module = "com.google.maps.android:android-maps-utils", version.ref = "androidMapsUtils" }
gms-googleServices = { module = "com.google.gms:google-services", version.ref = "gmsGoogleServices" }
gms-playServicesMlkitTextRecognition = { module = "com.google.android.gms:play-services-mlkit-text-recognition", version.ref = "gmsPlayServicesMlkitTextRecognition" }

gms-playServicesAuth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
gms-playServicesAuthApiPhone = { module = "com.google.android.gms:play-services-auth-api-phone", version.ref = "playServicesAuthApiPhone" }
gms-playServicesLocation = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
gms-playServicesPlaces = { module = "com.google.android.gms:play-services-places", version.ref = "playServicesPlaces" }

hms-location = { module = "com.huawei.hms:location", version.ref = "hmsLocation" }
hms-maps = { module = "com.huawei.hms:maps", version.ref = "hmsMaps" }

facebook-shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "facebookShimmer" }
support-multidex = { module = "com.android.support:multidex", version.ref = "suportMultidex" }
firebase-messagingKtx = { module = "com.google.firebase:firebase-messaging-ktx", version.ref = "firebaseMessagingKtx" }
firebase-firestoreKtx = { module = "com.google.firebase:firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }

dynatrace-agentAndroid = { module = "com.dynatrace.agent:agent-android", version.ref = "dynatraceAgentAndroid" }
dynatrace-gradlePlugin = { module = "com.dynatrace.tools.android:gradle-plugin", version.ref = "dynatraceGradlePlugin" }

androidGradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }

gradleMavenPluginPublish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "gradleMavenPluginPublish" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jfrog-buildInfoExtractorGradle = { module = "org.jfrog.buildinfo:build-info-extractor-gradle", version.ref = "jfrogBuildInfoExtractorGradle" }

jetbrains-kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
jetbrains-kotlinxMetadataJvm = { module = "org.jetbrains.kotlinx:kotlinx-metadata-jvm", version.ref = "jetbrainsKotlinxMetadataJvm" }

airbnb-lottie = { module = "com.airbnb.android:lottie", version.ref = "airbnbLottie" }
workRuntime = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }
workRuntimeKtx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntime" }

test-jUnit = { module = "junit:junit", version.ref = "testJUnit" }
test-mockitoCore = { module = "org.mockito:mockito-core", version.ref = "testMockitoCore" }
test-mockitoInline = { module = "org.mockito:mockito-inline", version.ref = "testMockitoInline" }
nhaarman-test-mockitoKotlin = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "nhaarmanTestMockitoKotlin" }
jetbrains-test-kotlinxCoroutineTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "jetbrainsTestKotlinxCoroutineTest" }
androidx-arch-coreTesting = { module = "androidx.arch.core:core-testing", version.ref = "androidArchCoreTesting" }
io-mockk = { module = "io.mockk:mockk", version.ref = "ioMockk" }
squareup-okhttp3-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserver" }
test-app-cash-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
test-hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
test-assertj-assertjCore = { module = "org.assertj:assertj-core", version.ref = "assertjCore" }
androidx-test-jUnit = { module = "androidx.test.ext:junit", version.ref = "androidxTestjUnit" }

androidTest-runner = { module = "androidx.test:runner", version.ref = "androidTestRunner" }
androidx-test-expresso-expressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxTestExpressoCore" }

guardsquare-dexguardGradlePlugin = { module = "com.guardsquare:dexguard-gradle-plugin", version.ref = "guardsquareDexguardGradlePlugin" }
guardsquare-dexguardRasp = { module = "com.guardsquare:dexguard-rasp", version.ref = "guardsquareDexguard" }
guardsquare-dexguardRuntime = { module = "com.guardsquare:dexguard-runtime", version.ref = "guardsquareDexguard" }

jetbrains-kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "jetbrainsKotlinxCoroutines" }
jetbrains-kotlinxCoroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "jetbrainsKotlinxCoroutines" }

adobe-analytics = { module = "com.adobe.marketing.mobile:analytics", version.ref = "adobeAnalytics" }
adobe-mobileservices = { module = "com.adobe.marketing.mobile:mobileservices", version.ref = "adobeMobileservices" }
adobe-userprofile = { module = "com.adobe.marketing.mobile:userprofile", version.ref = "adobeUserprofile" }
adobe-sdkCore = { module = "com.adobe.marketing.mobile:sdk-core", version.ref = "adobeSdkCore" }
adobe-target = { module = "com.adobe.marketing.mobile:target", version.ref = "adobeTarget" }

rsa-cryptojce = { module = "com.rsa:cryptojce", version.ref = "rsa" }
rsa-cryptojcommon = { module = "com.rsa:cryptojcommon", version.ref = "rsa" }
rsa-sslj = { module = "com.rsa:sslj", version.ref = "rsa" }
rsa-mfaSecurIDLib = { module = "com.rsa:mfasecuridlib", version.ref = "mfaSecurIDLib" }
rsa-mfaSecurIDLib-extension = { module = "com.rsa:mfasecuridlib-extension", version.ref = "mfaSecurIDLib" }

gradle-pluginPublish = { module = "com.gradle.publish:plugin-publish-plugin", version.ref = "gradlePluginPublish" }
github-dcendents-androidMavenGradlePlugin = { module = "com.github.dcendents:android-maven-gradle-plugin", version.ref = "dcendentsAndroidMavenGradlePlugin" }

gitlab-arturbosch-detektGradlePlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detektGradlePlugin" }

huawei-agcp = { module = "com.huawei.agconnect:agcp", version.ref = "huaweiAgcp" }

sonarsource-sonarqubeGradlePlugin = { module = "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin", version.ref = "sonarqubeGradlePlugin" }

jacksonCore-jacksonDatabind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jacksonCoreJacksonDatabind" }

io-coilKt-coilSvg = { module = "io.coil-kt:coil-svg", version.ref = "coilSvg" }

facebook-sdkCore={ module ="com.facebook.android:facebook-android-sdk" , version.ref="facebookSdkCore"}

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseVersionBoom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-common-ktx = { group = "com.google.firebase", name = "firebase-common-ktx" }
firebase-crashlytics-gradle = { group = "com.google.firebase", name = "firebase-crashlytics-gradle",version.ref = "firebaseGradle" }