[versions]

appcompat = "1.3.0"
coreKtx = "1.3.2"
browser = "1.3.0"
constraintlayout = "2.1.4"
biometric = "1.0.1"
androidxViewpager2 = "1.0.0"
coreSplashscreen = "1.0.0"
annotation = "1.5.0"

lifecycleExtensions = "2.1.0"
lifecycleViewmodelKtx = "2.2.0"
lifecycleCommonJava8 = "2.4.1"

supportCardViewV7 = "29.0.0"

navigationFragmentKtx = "2.5.1"
navigationUiKtx = "2.5.1"
navigationDynamicFeaturesFragment = "2.5.1"
navigationSafeArgsGradlePlugin = "2.5.1"

googlePlayCore = "1.8.2"
material = "1.4.0"
googlePlayCoreKtx = "1.8.1"
gmsGoogleServices = "4.3.14"
gmsPlayServicesMlkitTextRecognition = "18.0.0"

playServicesAuth = "20.3.0"
playServicesAuthApiPhone = "18.0.1"
playServicesLocation = "17.1.0"
playServicesPlaces = "17.0.0"

hmsLocation = "6.7.0.300"
hmsMaps = "5.0.3.302"

facebookShimmer = "0.5.0"

suportMultidex = "1.0.3"

firebaseMessagingKtx = "20.3.0"
firebaseFirestoreKtx = "24.2.2"

androidMapsUtils = "2.1.0"
artifactory-plugin = "4.1.1"
compileSdk = "31"

dynatraceAgentAndroid = "8.247.1.1003"
dynatraceGradlePlugin = "8.247.1.1003"

androidGradlePlugin = "7.3.1"
gradleMavenPluginPublish = "0.18.0"
gson = "2.8.2"
jfrogBuildInfoExtractorGradle = "4.15.1"
jvmTarget = "1.8"
kotlin = "1.6.21"

airbnbLottie = "5.0.3"

mbbk-plugin = "1.0.1.lts"
minSdk = "24"

roomCompiler = "2.2.5"
roomKtx = "2.2.5"
roomRuntime = "2.2.5"
targetSdk = "31"
workRuntime = "2.7.0"

testJUnit = "4.13.2"
testMockitoCore = "3.3.3"
testMockitoInline = "3.3.3"
nhaarmanTestMockitoKotlin = "2.2.0"
jetbrainsTestKotlinxCoroutineTest = "1.6.1"
androidArchCoreTesting = "2.1.0"

androidTestRunner = "1.5.1"
androidTestExpressoCore = "3.5.0"

guardsquareDexguardGradlePlugin = "1.2.9"
guardsquareDexguard = "9.2.9"

jetbrainsKotlinxCoroutines = "1.3.4"

adobeAnalytics = "1.2.10"
adobeMobileservices = "1.1.5"
adobeUserprofile = "1.1.0"
adobeSdkCore = "1.11.0"

rsa = "6.2.5"
rsaSecurIDLib = "2.8.0"

gradlePluginPublish = "0.9.9"
dcendentsAndroidMavenGradlePlugin = "1.5"

jetbrainsKotlinxMetadataJvm = "0.1.0"

detektGradlePlugin = "1.15.0"

huaweiAgcp = "1.5.2.300"

sonarqubeGradlePlugin = "2.6.1"

facephi = "6.0"