[plugins]
mbbk = { id = "com.bcp.bank.mbbk", version.ref = "mbbk-plugin" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
jetbrains-kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize",  version.ref = "kotlin"  }
hilt-android = {id = "com.google.dagger.hilt.android", version.ref = "hilt" }
firebase-crashlytics = {id = "com.google.firebase.crashlytics",version.ref = "firebaseGradle"}
google-services = {id = "com.google.gms.google-services",version.ref = "gmsGoogleServices"}
android-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigationSafeArgsGradlePlugin" }
